USE barangay_service_request_system;

CREATE TABLE IF NOT EXISTS community_posts (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(180) NOT NULL,
    slug VARCHAR(200) NOT NULL UNIQUE,
    category ENUM('announcement', 'event', 'program', 'advisory', 'resource') NOT NULL DEFAULT 'announcement',
    excerpt VARCHAR(255) NULL,
    content TEXT NOT NULL,
    image_path VARCHAR(255) NULL,
    event_date DATE NULL,
    event_time TIME NULL,
    venue VARCHAR(160) NULL,
    organizer VARCHAR(160) NULL,
    resource_link VARCHAR(255) NULL,
    is_featured TINYINT(1) NOT NULL DEFAULT 0,
    is_published TINYINT(1) NOT NULL DEFAULT 0,
    published_at DATETIME NULL,
    created_by INT UNSIGNED NULL,
    updated_by INT UNSIGNED NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    INDEX idx_community_posts_category (category),
    INDEX idx_community_posts_published (is_published),
    INDEX idx_community_posts_published_at (published_at),
    INDEX idx_community_posts_featured (is_featured),
    INDEX idx_community_posts_event_date (event_date),
    INDEX idx_community_posts_created_by (created_by),
    INDEX idx_community_posts_updated_by (updated_by),
    CONSTRAINT fk_community_posts_created_by
        FOREIGN KEY (created_by) REFERENCES users(id)
        ON DELETE SET NULL
        ON UPDATE CASCADE,
    CONSTRAINT fk_community_posts_updated_by
        FOREIGN KEY (updated_by) REFERENCES users(id)
        ON DELETE SET NULL
        ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO community_posts (
    title,
    slug,
    category,
    excerpt,
    content,
    event_date,
    event_time,
    venue,
    organizer,
    resource_link,
    is_featured,
    is_published,
    published_at,
    created_by,
    updated_by,
    created_at,
    updated_at
) VALUES
(
    'Online Barangay Services Are Now Available',
    'online-barangay-services-are-now-available',
    'announcement',
    'Residents can now request certificates, track status updates, and submit requirements online.',
    'The barangay service request system is available for residents who need clearances, certificates, and other standard barangay documents. Create an account, choose a service, upload requirements, and track the progress from your resident dashboard.',
    NULL,
    NULL,
    NULL,
    'Barangay Office',
    NULL,
    1,
    1,
    NOW(),
    (SELECT id FROM users WHERE email = 'admin@barangay.local' LIMIT 1),
    (SELECT id FROM users WHERE email = 'admin@barangay.local' LIMIT 1),
    NOW(),
    NOW()
),
(
    'Community Clean-up Drive',
    'community-clean-up-drive',
    'event',
    'Join the upcoming barangay clean-up activity with neighbors and volunteers.',
    'Residents are invited to join the community clean-up drive. Bring comfortable clothes, water, and basic cleaning tools if available. Assembly will be at the barangay hall before volunteers are assigned to nearby zones.',
    DATE_ADD(CURDATE(), INTERVAL 14 DAY),
    '08:00:00',
    'Barangay Hall Covered Court',
    'Barangay Council',
    NULL,
    1,
    1,
    NOW(),
    (SELECT id FROM users WHERE email = 'admin@barangay.local' LIMIT 1),
    (SELECT id FROM users WHERE email = 'admin@barangay.local' LIMIT 1),
    NOW(),
    NOW()
),
(
    'Water Interruption Advisory',
    'water-interruption-advisory',
    'advisory',
    'Prepare stored water ahead of the scheduled maintenance window.',
    'A temporary water interruption may affect selected streets due to maintenance work. Residents are advised to store enough water for household needs and follow barangay updates for changes to the schedule.',
    NULL,
    NULL,
    NULL,
    'Barangay Information Desk',
    NULL,
    0,
    1,
    NOW(),
    (SELECT id FROM users WHERE email = 'admin@barangay.local' LIMIT 1),
    (SELECT id FROM users WHERE email = 'admin@barangay.local' LIMIT 1),
    NOW(),
    NOW()
),
(
    'Resident Guide: Required IDs and Proof of Residency',
    'resident-guide-required-ids-and-proof-of-residency',
    'resource',
    'A quick guide to common documents needed for barangay transactions.',
    'For most barangay services, residents should prepare a valid ID and proof of residency. Acceptable proof may include a utility bill, lease document, barangay record, or other document showing the resident address.',
    NULL,
    NULL,
    'Barangay Hall',
    'Barangay Records Desk',
    NULL,
    0,
    1,
    NOW(),
    (SELECT id FROM users WHERE email = 'admin@barangay.local' LIMIT 1),
    (SELECT id FROM users WHERE email = 'admin@barangay.local' LIMIT 1),
    NOW(),
    NOW()
)
ON DUPLICATE KEY UPDATE
    title = VALUES(title),
    category = VALUES(category),
    excerpt = VALUES(excerpt),
    content = VALUES(content),
    event_date = VALUES(event_date),
    event_time = VALUES(event_time),
    venue = VALUES(venue),
    organizer = VALUES(organizer),
    resource_link = VALUES(resource_link),
    is_featured = VALUES(is_featured),
    is_published = VALUES(is_published),
    published_at = VALUES(published_at),
    updated_by = VALUES(updated_by),
    updated_at = NOW();
